### ISSUE TITLE
Is it repeated? If it is, it is recommended that the modified

### ISSUE THREAD

**Issue by jCodeLife** [shengxinjing/it-roadmap#44]
- 位置：实战进阶-性能优化-第一段
- 说明：关于性能优化的第一段的内容开口就是浏览器，这与下一部分（实战进阶-浏览器）第一段的内容一模一样，不知是否书写的的时候写重复了，如果是，建议修改，阅读体验更佳一些

![1639621716(1)](https://user-images.githubusercontent.com/50767049/146297287-f9fada0d-fbe9-4cd0-bd96-10f3bd78d549.jpg)

**Comment by gebilaofan** [comment]
看了一下代码  性能优化这块确实多复制了  已经提pr看大圣改不改

**Comment by shengxinjing** [comment]
确实是重复了 囧 感谢
